spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3307/sell?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    #url: jdbc:mysql://10.148.8.39:3307/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell





